language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
script:
  - py.test runtests.py --doctest-modules -v --cov cooper --cov-report term-missing
after_success:
  - coveralls
