language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
script:
  - coverage run runtests.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
