language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
script:
  - coverage run --branch --source=cooper runtests.py
after_success:
  - coveralls
  - codecov
